/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-XMP.h
 #	source generated by 4D Plugin Wizard
 #	Project : XMP
 #	author : miyako
 #	2023/05/15
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_XMP_H
#define PLUGIN_XMP_H

#include "4DPluginAPI.h"
#include "exempi-2.0/exempi/xmp.h"

#pragma mark -

void Exempi(PA_PluginParameters params);

#endif /* PLUGIN_XMP_H */
