/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-XMP.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : XMP
 #	author : miyako
 #	2023/05/15
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-XMP.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- XMP
            
			case 1 :
				Exempi(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void Exempi(PA_PluginParameters params) {

}

